// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using TiendaAlquiler.Models;



namespace TiendaAlquiler.Data;

public class TiendaAlquilerDBContext : IdentityDbContext<Usuario>
{
    public TiendaAlquilerDBContext(DbContextOptions<TiendaAlquilerDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Alquiler> Alquilers { get; set; }

    public virtual DbSet<Carroceria> Carroceria { get; set; }

    public virtual DbSet<Coche> Coches { get; set; }

    public virtual DbSet<Color> Colors { get; set; }

    public virtual DbSet<Decada> Decada { get; set; }

    public virtual DbSet<Foto> Fotos { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    public virtual DbSet<Pais> Paises { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Alquiler>(entity =>
        {
            base.OnModelCreating(modelBuilder);
            entity.HasKey(e => e.AlquilerId).HasName("PK__Alquiler__F28020B524CE1122");

            entity.ToTable("Alquiler");

            entity.Property(e => e.PrecioFinal).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Coche).WithMany(p => p.Alquilers)
                .HasForeignKey(d => d.CocheId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Alquiler_Coche");

            entity.HasOne(d => d.Usuario).WithMany(p => p.Alquilers)
                .HasForeignKey(d => d.UsuarioId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Alquiler_Usuario");
        });

        modelBuilder.Entity<Carroceria>(entity =>
        {
            entity.HasKey(e => e.CarroceriaId).HasName("PK__Carrocer__EBEFDD7F34F2C214");

            entity.Property(e => e.Tipo)
                .IsRequired()
                .HasMaxLength(30);
        });

        modelBuilder.Entity<Coche>(entity =>
        {
            entity.HasKey(e => e.CocheId).HasName("PK__Coche__9E980F6B023783F5");

            entity.ToTable("Coche");

            entity.Property(e => e.Marca)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Modelo)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PrecioAlquiler).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Carroceria).WithMany(p => p.Coches)
                .HasForeignKey(d => d.CarroceriaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Coche_Carroceria");

            entity.HasOne(d => d.Color).WithMany(p => p.Coches)
                .HasForeignKey(d => d.ColorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Coche_Color");

            entity.HasOne(d => d.Decada).WithMany(p => p.Coches)
                .HasForeignKey(d => d.DecadaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Coche_Decada");

            entity.HasOne(d => d.Pais).WithMany(p => p.Coches)
                .HasForeignKey(d => d.PaisId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Coche_Pais");
        });

        modelBuilder.Entity<Color>(entity =>
        {
            entity.HasKey(e => e.ColorId).HasName("PK__Color__8DA7674D8D39398E");

            entity.ToTable("Color");

            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<Decada>(entity =>
        {
            entity.HasKey(e => e.DecadaId).HasName("PK__Decada__B60F61813E1A9096");
        });

        modelBuilder.Entity<Foto>(entity =>
        {
            entity.HasKey(e => e.FotoId).HasName("PK__Foto__4EA1C119D86B5C92");

            entity.ToTable("Foto");

            entity.Property(e => e.RutaAcceso)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Coche).WithMany(p => p.Fotos)
                .HasForeignKey(d => d.CocheId)
                .HasConstraintName("FK_Foto_Coche");
        });

        modelBuilder.Entity<Pais>(entity =>
        {
            entity.HasKey(e => e.PaisId).HasName("PK__Pais__E30419353E3D377E");

            entity.ToTable("Pais");

            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Decada>().HasData(
            new Decada { DecadaId = 1, AnioInicio = 1910 },
            new Decada { DecadaId = 2, AnioInicio = 1920 },
            new Decada { DecadaId = 3, AnioInicio = 1930 },
            new Decada { DecadaId = 4, AnioInicio = 1940 },
            new Decada { DecadaId = 5, AnioInicio = 1950 },
            new Decada { DecadaId = 6, AnioInicio = 1960 },
            new Decada { DecadaId = 7, AnioInicio = 1970 },
            new Decada { DecadaId = 8, AnioInicio = 1980 },
            new Decada { DecadaId = 9, AnioInicio = 1990 },
            new Decada { DecadaId = 10, AnioInicio = 2000 }
            );


        modelBuilder.Entity<Color>().HasData(
            new Color { ColorId = 1, Nombre = "Rojo Ferrari" },
            new Color { ColorId = 2, Nombre = "British Racing Green" },
            new Color { ColorId = 3, Nombre = "Silver Ghost" },
            new Color { ColorId = 4, Nombre = "Blue Subaru" },
            new Color { ColorId = 5, Nombre = "Negro Medianoche" },
            new Color { ColorId = 6, Nombre = "Amarillo" },
            new Color { ColorId = 7, Nombre = "White Cream" },
            new Color { ColorId = 8, Nombre = "Marron" }
            );


        modelBuilder.Entity<Carroceria>().HasData(
            new Carroceria { CarroceriaId = 1, Tipo = "Coupe" },
            new Carroceria { CarroceriaId = 2, Tipo = "Targa" },
            new Carroceria { CarroceriaId = 3, Tipo = "Descapotable" },
            new Carroceria { CarroceriaId = 4, Tipo = "Berlinetta" },
            new Carroceria { CarroceriaId = 5, Tipo = "HacthBack" },
            new Carroceria { CarroceriaId = 6, Tipo = "GT" },
            new Carroceria { CarroceriaId = 7, Tipo = "Urbano" },
            new Carroceria { CarroceriaId = 8, Tipo = "MicroCoche" }
            );


        modelBuilder.Entity<Pais>().HasData(
            new Pais { PaisId = 1, Nombre = "España" },
            new Pais { PaisId = 2, Nombre = "Italia" },
            new Pais { PaisId = 3, Nombre = "Francia" },
            new Pais { PaisId = 4, Nombre = "Reino Unido" },
            new Pais { PaisId = 5, Nombre = "Alemania" },
            new Pais { PaisId = 6, Nombre = "Estados Unidos" },
            new Pais { PaisId = 7, Nombre = "Japon" },
            new Pais { PaisId = 8, Nombre = "Holanda" },
            new Pais { PaisId = 9, Nombre = "Belgica" },
            new Pais { PaisId = 10, Nombre = "Portugal" },
            new Pais { PaisId = 11, Nombre = "Korea" }
            );


        modelBuilder.Entity<Coche>().HasData(
            new Coche { CocheId = 1, Marca = "Ferrari", Modelo = "F40", AnioFabricacion = 1984, CarroceriaId = 4, ColorId = 1, PaisId = 2, DecadaId = 8, PrecioAlquiler = 1500, EstaAlquilado = false },

            new Coche { CocheId = 2, Marca = "Aston Martin", Modelo = "DB5", AnioFabricacion = 1963, CarroceriaId = 6, ColorId = 3, PaisId = 4, DecadaId = 6, PrecioAlquiler = 3000, EstaAlquilado = false },

            new Coche { CocheId = 3, Marca = "Porsche", Modelo = "911", AnioFabricacion = 1970, CarroceriaId = 6, ColorId = 6, PaisId = 5, DecadaId = 7, PrecioAlquiler = 2000, EstaAlquilado = false },

            new Coche { CocheId = 4, Marca = "Ferrari", Modelo = "250 GTO", AnioFabricacion = 1955, CarroceriaId = 4, ColorId = 1, PaisId = 2, DecadaId = 5, PrecioAlquiler = 300, EstaAlquilado = false },

            new Coche { CocheId = 5, Marca = "Jaguar", Modelo = "E-Type", AnioFabricacion = 1958, CarroceriaId = 3, ColorId = 2, PaisId = 4, DecadaId = 5, PrecioAlquiler = 250, EstaAlquilado = false },

            new Coche { CocheId = 6, Marca = "Rolls Royce", Modelo = "Silver Cloud", AnioFabricacion = 1980, CarroceriaId = 3, ColorId = 3, PaisId = 3, DecadaId = 8, PrecioAlquiler = 400, EstaAlquilado = false },

            new Coche { CocheId = 7, Marca = "Subaru", Modelo = "Impreza WRX", AnioFabricacion = 1999, CarroceriaId = 5, ColorId = 4, PaisId = 7, DecadaId = 9, PrecioAlquiler = 120, EstaAlquilado = false },

            new Coche { CocheId = 8, Marca = "Mercedes-Benz", Modelo = "300 SL", AnioFabricacion = 1955, CarroceriaId = 2, ColorId = 5, PaisId = 5, DecadaId = 5, PrecioAlquiler = 350, EstaAlquilado = false },

            new Coche { CocheId = 9, Marca = "Austin", Modelo = "Mini Cooper", AnioFabricacion = 1966, CarroceriaId = 7, ColorId = 8, PaisId = 4, DecadaId = 6, PrecioAlquiler = 100, EstaAlquilado = false },

            new Coche { CocheId = 10, Marca = "Ford", Modelo = "Mustang", AnioFabricacion = 1967, CarroceriaId = 6, ColorId = 1, PaisId = 6, DecadaId = 6, PrecioAlquiler = 500, EstaAlquilado = false },

            new Coche { CocheId = 11, Marca = "Chevrolet", Modelo = "Camaro", AnioFabricacion = 1969, CarroceriaId = 6, ColorId = 2, PaisId = 6, DecadaId = 6, PrecioAlquiler = 450, EstaAlquilado = false },

            new Coche { CocheId = 12, Marca = "Volkswagen", Modelo = "Beetle", AnioFabricacion = 1950, CarroceriaId = 7, ColorId = 8, PaisId = 5, DecadaId = 5, PrecioAlquiler = 100, EstaAlquilado = false },

            new Coche { CocheId = 13, Marca = "Alfa Romeo", Modelo = "Giulia", AnioFabricacion = 1975, CarroceriaId = 4, ColorId = 5, PaisId = 2, DecadaId = 7, PrecioAlquiler = 200, EstaAlquilado = false },

            new Coche { CocheId = 14, Marca = "Mazda", Modelo = "RX-7", AnioFabricacion = 1992, CarroceriaId = 5, ColorId = 4, PaisId = 7, DecadaId = 9, PrecioAlquiler = 300, EstaAlquilado = false },

            new Coche { CocheId = 15, Marca = "BMW", Modelo = "2002", AnioFabricacion = 1972, CarroceriaId = 6, ColorId = 6, PaisId = 5, DecadaId = 7, PrecioAlquiler = 220, EstaAlquilado = false },

            new Coche { CocheId = 16, Marca = "Citroën", Modelo = "2CV", AnioFabricacion = 1957, CarroceriaId = 7, ColorId = 7, PaisId = 3, DecadaId = 5, PrecioAlquiler = 120, EstaAlquilado = false },

            new Coche { CocheId = 17, Marca = "Lancia", Modelo = "Stratos", AnioFabricacion = 1973, CarroceriaId = 6, ColorId = 1, PaisId = 2, DecadaId = 7, PrecioAlquiler = 600, EstaAlquilado = false },

            new Coche { CocheId = 18, Marca = "Fiat", Modelo = "500", AnioFabricacion = 1968, CarroceriaId = 7, ColorId = 2, PaisId = 2, DecadaId = 6, PrecioAlquiler = 150, EstaAlquilado = false },

            new Coche { CocheId = 19, Marca = "DeLorean", Modelo = "DMC-12", AnioFabricacion = 1981, CarroceriaId = 6, ColorId = 3, PaisId = 6, DecadaId = 8, PrecioAlquiler = 800, EstaAlquilado = false },

            new Coche { CocheId = 20, Marca = "Toyota", Modelo = "Supra", AnioFabricacion = 1994, CarroceriaId = 6, ColorId = 4, PaisId = 7, DecadaId = 9, PrecioAlquiler = 400, EstaAlquilado = false },

            new Coche { CocheId = 21, Marca = "Peugeot", Modelo = "205 GTI", AnioFabricacion = 1988, CarroceriaId = 5, ColorId = 6, PaisId = 3, DecadaId = 8, PrecioAlquiler = 180, EstaAlquilado = false },

            new Coche { CocheId = 22, Marca = "Renault", Modelo = "Alpine A110", AnioFabricacion = 1965, CarroceriaId = 6, ColorId = 5, PaisId = 3, DecadaId = 6, PrecioAlquiler = 300, EstaAlquilado = false },

            new Coche { CocheId = 23, Marca = "Bugatti", Modelo = "Type 35", AnioFabricacion = 1932, CarroceriaId = 6, ColorId = 3, PaisId = 3, DecadaId = 3, PrecioAlquiler = 1000, EstaAlquilado = false },

            new Coche { CocheId = 24, Marca = "Lamborghini", Modelo = "Miura", AnioFabricacion = 1969, CarroceriaId = 6, ColorId = 1, PaisId = 2, DecadaId = 6, PrecioAlquiler = 2000, EstaAlquilado = false },

            new Coche { CocheId = 25, Marca = "Mitsubishi", Modelo = "Lancer Evolution VI", AnioFabricacion = 1998, CarroceriaId = 5, ColorId = 4, PaisId = 7, DecadaId = 9, PrecioAlquiler = 250, EstaAlquilado = false },

            new Coche { CocheId = 26, Marca = "Nissan", Modelo = "Skyline GT-R", AnioFabricacion = 1995, CarroceriaId = 5, ColorId = 5, PaisId = 7, DecadaId = 9, PrecioAlquiler = 450, EstaAlquilado = false },

            new Coche { CocheId = 27, Marca = "Cadillac", Modelo = "Eldorado", AnioFabricacion = 1959, CarroceriaId = 3, ColorId = 7, PaisId = 6, DecadaId = 5, PrecioAlquiler = 600, EstaAlquilado = false },

            new Coche { CocheId = 28, Marca = "Volvo", Modelo = "P1800", AnioFabricacion = 1961, CarroceriaId = 6, ColorId = 3, PaisId = 8, DecadaId = 6, PrecioAlquiler = 200, EstaAlquilado = false },

            new Coche { CocheId = 29, Marca = "Honda", Modelo = "NSX", AnioFabricacion = 1991, CarroceriaId = 6, ColorId = 1, PaisId = 7, DecadaId = 9, PrecioAlquiler = 350, EstaAlquilado = false }

            );

    }

}