// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace TiendaAlquiler.Models;

public partial class Alquiler
{
    [Key]
    public int AlquilerId { get; set; }
    [Required]
    public int CocheId { get; set; }
    [Required]
    public string UsuarioId { get; set; }

    [Required(ErrorMessage = "La fecha de inicio es obligatoria")]
    [DataType(DataType.Date)]
    public DateOnly FechaAlquiler { get; set; }

    [DataType(DataType.Date)]
    [Required(ErrorMessage = "La fecha de devolucion es obligatoria")]
    public DateOnly FechaDevolucion { get; set; }

    [Required]
    [Range(0, double.MaxValue, ErrorMessage = "El precio final debe ser un valor positivo.")]
    public decimal PrecioFinal { get; set; }

    public virtual Coche Coche { get; set; }

    public virtual Usuario Usuario { get; set; }
    public Alquiler()
    {
        FechaAlquiler = DateOnly.FromDateTime(DateTime.Now);
        FechaDevolucion = DateOnly.FromDateTime(DateTime.Now);
    }
}