// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace TiendaAlquiler.Models;

public partial class Carroceria
{
    [Key]
    public int CarroceriaId { get; set; }
    [Required]
    public string Tipo { get; set; }

    public virtual ICollection<Coche> Coches { get; set; } = new List<Coche>();
}