// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace TiendaAlquiler.Models;

public partial class Carroceria
{
    [Key]
    public int CarroceriaId { get; set; }

    [Required(ErrorMessage = "El tipo de carroceria tiene que ser obligatorio")]
    [StringLength(50, ErrorMessage = "El nombre de la carroceria no puede exceder de 50 letras")]
    [RegularExpression(@"^[A-Za-zÁáÉéÍíÓóÚúÑñ\s]+$", ErrorMessage = "El tipo de carrocería solo puede contener letras y espacios.")]
    public string Tipo { get; set; }

    public virtual ICollection<Coche> Coches { get; set; } = new List<Coche>();
}