// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace TiendaAlquiler.Models;

public partial class Coche
{
    [Key]
    public int CocheId { get; set; }
    

    [Required]
    public string Marca { get; set; }
    
    [Required]
    public string Modelo { get; set; }
    
    [Required]
    public int AnioFabricacion { get; set; }
    
    [Required]
    [Range(0.01, double.MaxValue, ErrorMessage = "El precio de alquiler debe ser mayor a cero.")]
    [Column(TypeName = "decimal(18,2)")]
    public decimal PrecioAlquiler { get; set; }

    public bool EstaAlquilado { get; set; }
    
    [Required]
    public int ColorId { get; set; }
    
    [Required]
    public int CarroceriaId { get; set; }
    
    [Required]
    public int DecadaId { get; set; }
    [Required]
    public int PaisFabricacionId { get; set; }
    
    [Required]
    public virtual ICollection<Alquiler> Alquilers { get; set; } = new List<Alquiler>();

    public virtual Carroceria Carroceria { get; set; }

    public virtual Color Color { get; set; }

    public virtual Decada Decada { get; set; }

    public virtual ICollection<Foto> Fotos { get; set; } = new List<Foto>();

    public virtual PaisFabricacion PaisFabricacion { get; set; }
}