// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace TiendaAlquiler.Models;

public partial class Decada
{
    [Key]
    public int DecadaId { get; set; }

    [Required(ErrorMessage = "El año de inicio es obligatorio.")]
    [Range(1900, 2100, ErrorMessage = "El año de inicio debe estar entre 1900 y 2100.")]
    public int AnioInicio { get; set; }

    public virtual ICollection<Coche> Coches { get; set; } = new List<Coche>();
}