// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TiendaAlquiler.Models;

public partial class Foto
{
    [Key]
    public int FotoId { get; set; }

    [Required(ErrorMessage = " El id del coche es obligatorio.")]
    public int CocheId { get; set; }
    public string RutaAcceso { get; set; }
    public virtual Coche Coche { get; set; }
}