// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TiendaAlquiler.Models;

public partial class Pais
{
    [Key]
    public int PaisId { get; set; }

    [Required(ErrorMessage = "El nombre del país es obligatorio.")]
    [StringLength(100, ErrorMessage = "El nombre del país no puede exceder los 100 caracteres.")]
    [RegularExpression(@"^[A-Za-zÁáÉéÍíÓóÚúÑñ\s]+$", ErrorMessage = "El Nombre del pais solo puede contener letras y espacios.")]

    public string Nombre { get; set; }

    public virtual ICollection<Coche> Coches { get; set; } = new List<Coche>();
}