// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TiendaAlquiler.Models;

public partial class PaisFabricacion
{
    [Key]
    public int PaisFabricacionId { get; set; }

    [Required(ErrorMessage = "El nombre del país es obligatorio.")]
    [StringLength(100, ErrorMessage = "El nombre del país no puede exceder los 100 caracteres.")]
    public string Nombre { get; set; }

    public virtual ICollection<Coche> Coches { get; set; } = new List<Coche>();
}